#! /usr/bin/env python
from __future__ import print_function
import os.path
import sys
import urllib
import subprocess

def usage():
  print("""usage: build-unicode-data <srcroot> <version> [<version> ...]

Fetches and generates Unicode Database files for libucd.""",
        file=sys.stderr)

def build_unicode(srcroot, versions):
  ucdc = os.path.join(srcroot, 'tools/ucdc')
  
  for version in versions:
    # Fetch the Unicode data
    for fname in ('UCD.zip', 'Unihan.zip'):
      url = 'http://www.unicode.org/Public/%s/ucd/%s' % (version, fname)
      abspath = os.path.join(srcroot, 'ucd/%s/%s' % (version, fname))
      
      if not os.path.isfile(abspath):
        urllib.urlretrieve(url, abspath)

    # Build it with ucdc
    target = os.path.join(srcroot,
                          'ucd/packed/unicode-%s.ucd' % version)
    if not os.path.isfile(target):
      subprocess.call([ucdc, version,
                       os.path.join(srcroot, 'ucd/%s' % version),
                       target])

if __name__ == '__main__':
  if len(sys.argv) < 3:
    usage()
    exit(1)
                    
  srcroot = sys.argv[1]
  versions = sys.argv[2:]

  build_unicode(srcroot, versions)
