#ifndef BINPROP
#define BINPROP(name, method, tag)
#endif

// Proplist.txt
BINPROP("ASCII_Hex_Digit", ascii_hex_digit, 'AHD?')
BINPROP("Bidi_Control", bidi_control, 'BCt?')
BINPROP("Dash", dash, 'Dsh?')
BINPROP("Deprecated", deprecated, 'Dep?')
BINPROP("Diacritic", diacritic, 'Dia?')
BINPROP("Extender", extender, 'Ext?')
BINPROP("Hex_Digit", hex_digit, 'Hex?')
BINPROP("Hyphen", hyphen, 'Hyp?')
BINPROP("Ideographic", ideographic, 'Ido?')
BINPROP("IDS_Binary_Operator", ids_binary_operator, 'IBO?')
BINPROP("IDS_Trinary_Operator", ids_trinary_operator, 'ITO?')
BINPROP("Join_Control", join_control, 'JCt?')
BINPROP("Logical_Order_Exception", logical_order_exception, 'LOE?')
BINPROP("Noncharacter_Code_Point", noncharacter_code_point, 'NCP?')
BINPROP("Other_Alphabetic", other_alphabetic, 'OAl?')
BINPROP("Other_Default_Ignorable_Code_Point", other_default_ignorable_code_point, 'ODI?')
BINPROP("Other_Grapheme_Extend", other_grapheme_extend, 'OGE?')
BINPROP("Other_ID_Continue", other_id_continue, 'OIC?')
BINPROP("Other_ID_Start", other_id_start, 'OIS?')
BINPROP("Other_Lowercase", other_lowercase, 'OLc?')
BINPROP("Other_Math", other_math, 'OMa?')
BINPROP("Other_Uppercase", other_uppercase, 'OUc?')
BINPROP("Pattern_Syntax", pattern_syntax, 'PSy?')
BINPROP("Pattern_White_Space", pattern_white_space, 'PWS?')
BINPROP("Prepended_Concatenation_Mark", prepended_concatenation_mark, 'PCM?')
BINPROP("Quotation_Mark", quotation_mark, 'QMa?')
BINPROP("Radical", radical, 'Rad?')
BINPROP("Soft_Dotted", soft_dotted, 'SDt?')
BINPROP("STerm", sterm, 'Stm?')
BINPROP("Terminal_Punctuation", terminal_punctuation, 'TPu?')
BINPROP("Unified_Ideograph", unified_ideograph, 'UId?')
BINPROP("Variation_Selector", variation_selector, 'VSl?')
BINPROP("White_Space", white_space, 'WSp?')

// DerivedCoreProperties.txt
BINPROP("Lowercase", lowercase, 'Lca?')
BINPROP("Uppercase", uppercase, 'Uca?')
BINPROP("Cased", cased, 'Cse?')
BINPROP("Case_Ignorable", case_ignorable, 'CIg?')
BINPROP("Changes_When_Lowercased", changes_when_lowercased, 'CWL?')
BINPROP("Changes_When_Uppercased", changes_when_uppercased, 'CWU?')
BINPROP("Changes_When_Titlecased", changes_when_titlecased, 'CWT?')
BINPROP("Changes_When_Casefolded", changes_when_casefolded, 'CWC?')
BINPROP("Changes_When_Casemapped", changes_when_casemapped, 'CWM?')
BINPROP("Alphabetic", alphabetic, 'Alp?')
BINPROP("Default_Ignorable_Code_Point", default_ignorable_code_point, 'DIC?')
BINPROP("Grapheme_Base", grapheme_base, 'GBa?')
BINPROP("Grapheme_Extend", grapheme_extend, 'GEx?')
BINPROP("Grapheme_Link", grapheme_link, 'GLi?')
BINPROP("Math", math, 'Mth?')
BINPROP("ID_Start", id_start, 'IDS?')
BINPROP("ID_Continue", id_continue, 'IDC?')
BINPROP("XID_Start", xid_start, 'XID?')
BINPROP("XID_Continue", xid_continue, 'XIC?')

/* CompositionExclusions.txt */
BINPROP("Composition_Exclusion", composition_exclusion, 'CEx?')

/* DerivedNormalizationProps.txt */
BINPROP("Full_Composition_Exclusion", full_composition_exclusion, 'FCx?')
BINPROP("Expands_On_NFD", expands_on_nfd, 'xND?')
BINPROP("Expands_On_NFC", expands_on_nfc, 'xNC?')
BINPROP("Expands_On_NFKD", expands_on_nfkd, 'xNd?')
BINPROP("Expands_On_NFKC", expands_on_nfkc, 'xNc?')
BINPROP("Changes_When_NFKC_Casefolded", changes_when_nfkc_casefolded, 'CWc?')

/* emoji-data.txt */
BINPROP("Emoji", emoji, 'Emj?')
BINPROP("Emoji_Presentation", emoji_presentation, 'EmP?')
BINPROP("Emoji_Modifier", emoji_modifier, 'EmM?')
BINPROP("Emoji_Modifier_Base", emoji_modifier_base, 'EmB?')
